# Generated by Django 4.2.30 on 2026-06-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearrecord',
            name='lens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wear_records', to='lens.lens', verbose_name='镜片'),
        ),
    ]
