# Generated by Django 4.2.30 on 2026-06-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0002_change_lens_fk_to_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='care_method',
            field=models.CharField(blank=True, choices=[('hydrogen_peroxide', '双氧水护理'), ('multi_purpose', '多功能护理液'), ('daily_disposable', '日抛无需护理'), ('other', '其他方式')], default='', max_length=30, null=True, verbose_name='护理方式'),
        ),
        migrations.AddField(
            model_name='lens',
            name='care_solution_brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='护理液品牌'),
        ),
        migrations.AddField(
            model_name='lens',
            name='need_rest_observation',
            field=models.BooleanField(default=False, verbose_name='是否需要停戴观察'),
        ),
        migrations.AddField(
            model_name='lens',
            name='next_care_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次护理日期'),
        ),
        migrations.AddField(
            model_name='lens',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次眼科复查日期'),
        ),
        migrations.AddField(
            model_name='lens',
            name='replacement_days_after_open',
            field=models.IntegerField(blank=True, choices=[(1, '每天更换'), (7, '每周更换'), (14, '每2周更换'), (30, '每月更换'), (60, '每2月更换'), (90, '每季度更换'), (180, '每半年更换'), (365, '每年更换')], null=True, verbose_name='开封后建议更换周期(天)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='rest_until_date',
            field=models.DateField(blank=True, null=True, verbose_name='停戴至日期'),
        ),
        migrations.CreateModel(
            name='CareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('care', '护理提醒'), ('replacement', '更换提醒'), ('checkup', '复查提醒'), ('rest', '停戴提醒'), ('risk', '高风险提醒')], max_length=30, verbose_name='提醒类型')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('danger', '危险')], default='info', max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='是否已忽略')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lens.lens', verbose_name='镜片')),
                ('triggered_by_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_reminders', to='lens.wearrecord', verbose_name='触发记录')),
            ],
            options={
                'verbose_name': '护理提醒',
                'verbose_name_plural': '护理提醒',
                'db_table': 'care_reminder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('routine', '常规护理'), ('deep_clean', '深度清洁'), ('case_replace', '更换镜盒'), ('solution_replace', '更换护理液'), ('replacement', '镜片更换'), ('checkup', '眼科复查'), ('rest_start', '开始停戴观察'), ('rest_end', '结束停戴观察'), ('other', '其他')], max_length=30, verbose_name='护理类型')),
                ('care_date', models.DateField(verbose_name='护理/复查日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_records', to='lens.lens', verbose_name='镜片')),
            ],
            options={
                'verbose_name': '护理记录',
                'verbose_name_plural': '护理记录',
                'db_table': 'care_record',
                'ordering': ['-care_date', '-created_at'],
            },
        ),
    ]
