# Generated by Django 4.2.30 on 2026-06-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0003_lens_care_method_lens_care_solution_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(choices=[('daily', '日常通勤'), ('date', '约会'), ('party', '派对/聚会'), ('wedding', '婚礼/宴会'), ('photo', '拍照/写真'), ('travel', '旅行/出游'), ('interview', '面试/商务'), ('sports', '运动'), ('other', '其他')], default='daily', max_length=50, verbose_name='场景名称')),
                ('custom_scene_name', models.CharField(blank=True, default='', max_length=100, verbose_name='自定义场景')),
                ('makeup_style', models.CharField(choices=[('natural', '自然裸妆'), ('fresh', '清新淡妆'), ('elegant', '优雅知性'), ('sweet', '甜美可爱'), ('sexy', '性感妩媚'), ('cool', '酷飒欧美'), ('gothic', '哥特暗黑'), ('korean', '韩系妆容'), ('japanese', '日系妆容'), ('custom', '自定义风格')], default='natural', max_length=30, verbose_name='妆容风格')),
                ('custom_makeup_style', models.CharField(blank=True, default='', max_length=100, verbose_name='自定义妆容风格')),
                ('clothing_color', models.CharField(choices=[('warm', '暖色系'), ('cool', '冷色系'), ('neutral', '中性色系'), ('earth', '大地色系'), ('pastel', '马卡龙色系'), ('monochrome', '黑白灰'), ('bright', '鲜艳亮色'), ('mixed', '撞色搭配')], default='neutral', max_length=30, verbose_name='服饰色系')),
                ('lighting', models.CharField(choices=[('natural_day', '自然光(白天)'), ('natural_sunset', '自然光(黄昏)'), ('indoor_soft', '室内柔光'), ('indoor_bright', '室内强光'), ('neon', '霓虹灯光'), ('candle', '烛光/暖光'), ('flash', '闪光灯'), ('mixed', '混合光线')], default='natural_day', max_length=30, verbose_name='光线环境')),
                ('expected_wear_date', models.DateField(verbose_name='预计佩戴日期')),
                ('expected_duration_hours', models.FloatField(default=8.0, verbose_name='预计佩戴时长(小时)')),
                ('match_score', models.IntegerField(default=4, verbose_name='搭配评分(1-5)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已执行'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_outfit_plans', to='lens.lens', verbose_name='备选镜片')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_plans', to='lens.lens', verbose_name='推荐镜片')),
                ('wear_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_plan', to='lens.wearrecord', verbose_name='关联佩戴记录')),
            ],
            options={
                'verbose_name': '妆容搭配计划',
                'verbose_name_plural': '妆容搭配计划',
                'db_table': 'outfit_plan',
                'ordering': ['-expected_wear_date', '-created_at'],
            },
        ),
    ]
