# Generated by Django 4.2.30 on 2026-06-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0004_outfitplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='budget_month',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='预算月份'),
        ),
        migrations.AddField(
            model_name='lens',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='折扣(%)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='planned_restock_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划补货日期'),
        ),
        migrations.AddField(
            model_name='lens',
            name='purchase_channel',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='购买渠道'),
        ),
        migrations.AddField(
            model_name='lens',
            name='restock_notes',
            field=models.TextField(blank=True, default='', verbose_name='补货备注'),
        ),
        migrations.AddField(
            model_name='lens',
            name='restock_priority',
            field=models.CharField(choices=[('high', '高优先级'), ('medium', '中优先级'), ('low', '低优先级')], default='medium', max_length=20, verbose_name='补货优先级'),
        ),
        migrations.AddField(
            model_name='lens',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='运费(元)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='stock_quantity',
            field=models.IntegerField(default=2, verbose_name='库存数量(片)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实付金额(元)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价(元)'),
        ),
        migrations.AddField(
            model_name='lens',
            name='usage_frequency',
            field=models.CharField(choices=[('frequent', '常用'), ('occasional', '偶尔'), ('rare', '很少')], default='occasional', max_length=20, verbose_name='常用程度'),
        ),
        migrations.CreateModel(
            name='RestockSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('low_stock', '库存不足'), ('expiring_soon', '即将过期'), ('high_usage', '高频使用'), ('long_unused', '长期未用'), ('low_comfort', '低舒适度'), ('planned', '计划补货'), ('seasonal', '季节性补货')], max_length=30, verbose_name='建议类型')),
                ('severity', models.CharField(choices=[('critical', '紧急'), ('important', '重要'), ('normal', '常规')], default='normal', max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='建议内容')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('estimated_days_left', models.IntegerField(blank=True, null=True, verbose_name='预计可用天数')),
                ('suggested_quantity', models.IntegerField(default=2, verbose_name='建议补货数量')),
                ('suggested_date', models.DateField(blank=True, null=True, verbose_name='建议补货日期')),
                ('is_action_taken', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='是否已忽略')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('action_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('action_notes', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_suggestions', to='lens.lens', verbose_name='关联镜片')),
            ],
            options={
                'verbose_name': '补货建议',
                'verbose_name_plural': '补货建议',
                'db_table': 'restock_suggestion',
                'ordering': ['-severity', '-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('purchase_channel', models.CharField(choices=[('taobao', '淘宝'), ('tmall', '天猫'), ('jd', '京东'), ('pdd', '拼多多'), ('xiaohongshu', '小红书'), ('offline', '线下实体店'), ('other', '其他渠道')], default='taobao', max_length=50, verbose_name='购买渠道')),
                ('custom_channel', models.CharField(blank=True, default='', max_length=100, verbose_name='自定义渠道')),
                ('quantity', models.IntegerField(default=2, verbose_name='采购数量(片)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价(元)')),
                ('discount', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='折扣(%)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='运费(元)')),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='优惠券金额(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='商品总额(元)')),
                ('actual_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实付金额(元)')),
                ('payment_status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('refunded', '已退款')], default='paid', max_length=20, verbose_name='付款状态')),
                ('order_number', models.CharField(blank=True, default='', max_length=100, verbose_name='订单号')),
                ('budget_month', models.CharField(blank=True, default='', max_length=7, verbose_name='预算月份')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='lens.lens', verbose_name='关联镜片')),
            ],
            options={
                'verbose_name': '采购记录',
                'verbose_name_plural': '采购记录',
                'db_table': 'purchase_record',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
