# Generated by Django 4.2.30 on 2026-06-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0005_lens_budget_month_lens_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='旅行名称')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('start_date', models.DateField(verbose_name='出发日期')),
                ('end_date', models.DateField(verbose_name='返回日期')),
                ('climate', models.CharField(choices=[('tropical_humid', '热带潮湿'), ('subtropical_humid', '亚热带潮湿'), ('temperate', '温带温和'), ('dry_hot', '干燥炎热'), ('cold_dry', '寒冷干燥'), ('highland', '高原高海拔'), ('marine', '海洋性气候'), ('variable', '气候多变')], default='temperate', max_length=30, verbose_name='气候环境')),
                ('transport', models.CharField(choices=[('airplane', '飞机'), ('train', '火车/高铁'), ('car', '自驾'), ('bus', '长途大巴'), ('ship', '轮船/邮轮'), ('mixed', '多种交通')], default='airplane', max_length=30, verbose_name='交通方式')),
                ('luggage', models.CharField(choices=[('carry_on', '仅随身行李'), ('checked_small', '托运行李(小件)'), ('checked_large', '托运行李(大件)'), ('no_limit', '无限制')], default='carry_on', max_length=30, verbose_name='行李限制')),
                ('planned_wear_scene', models.CharField(choices=[('daily_sightseeing', '日常观光'), ('outdoor_activity', '户外活动'), ('beach_water', '海滩/水上活动'), ('formal_event', '正式场合/宴会'), ('photo_shoot', '拍照/写真'), ('business_meeting', '商务会议'), ('night_out', '夜生活/派对'), ('sports', '运动'), ('mixed', '混合场景')], default='daily_sightseeing', max_length=30, verbose_name='计划佩戴场景')),
                ('custom_wear_scene', models.CharField(blank=True, default='', max_length=100, verbose_name='自定义佩戴场景')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('planning', '计划中'), ('upcoming', '即将出发'), ('in_progress', '旅行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='状态')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中等风险'), ('high', '高风险')], default='low', max_length=20, verbose_name='风险等级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '旅行计划',
                'verbose_name_plural': '旅行计划',
                'db_table': 'travel_plan',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('care_solution', '护理液'), ('lens_case', '镜盒'), ('eye_drops', '润眼液/人工泪液'), ('hand_sanitizer', '洗手液'), ('tweezers', '镊子'), ('glasses', '框架眼镜'), ('saline', '生理盐水'), ('wet_wipes', '湿纸巾'), ('sunglasses', '太阳镜'), ('prescription_sunglasses', '有度数太阳镜'), ('other', '其他用品')], max_length=30, verbose_name='用品类型')),
                ('custom_name', models.CharField(blank=True, default='', max_length=100, verbose_name='自定义名称')),
                ('is_checked', models.BooleanField(default=False, verbose_name='是否已准备')),
                ('quantity', models.CharField(blank=True, default='', max_length=100, verbose_name='数量/规格')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='lens.travelplan', verbose_name='旅行计划')),
            ],
            options={
                'verbose_name': '旅行随身用品',
                'verbose_name_plural': '旅行随身用品',
                'db_table': 'travel_supply_item',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiry', '有效期提醒'), ('stock', '库存提醒'), ('climate', '气候提醒'), ('comfort', '舒适度提醒'), ('supply', '用品提醒'), ('care', '护理提醒'), ('schedule', '行程提醒'), ('other', '其他提醒')], max_length=30, verbose_name='提醒类型')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('danger', '危险')], default='info', max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='是否已忽略')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lens.lens', verbose_name='关联镜片')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='lens.travelplan', verbose_name='旅行计划')),
            ],
            options={
                'verbose_name': '旅行风险提醒',
                'verbose_name_plural': '旅行风险提醒',
                'db_table': 'travel_risk_alert',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelLensItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', '主带镜片'), ('backup', '备用镜片'), ('special', '特殊场景用')], default='primary', max_length=20, verbose_name='角色')),
                ('quantity', models.IntegerField(default=2, verbose_name='携带数量(片)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_items', to='lens.lens', verbose_name='镜片')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_items', to='lens.travelplan', verbose_name='旅行计划')),
            ],
            options={
                'verbose_name': '旅行携带镜片',
                'verbose_name_plural': '旅行携带镜片',
                'db_table': 'travel_lens_item',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='日期')),
                ('day_label', models.CharField(blank=True, default='', max_length=50, verbose_name='行程第几天')),
                ('planned_activity', models.CharField(blank=True, default='', max_length=200, verbose_name='当日主要活动')),
                ('expected_duration_hours', models.FloatField(default=8.0, verbose_name='预计佩戴时长(小时)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_wear_lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lens.lens', verbose_name='计划佩戴镜片')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='lens.travelplan', verbose_name='旅行计划')),
            ],
            options={
                'verbose_name': '旅行每日佩戴安排',
                'verbose_name_plural': '旅行每日佩戴安排',
                'db_table': 'travel_daily_plan',
                'ordering': ['plan_date', 'order_index'],
            },
        ),
    ]
